services:
    todo-frontend:
        build:
          context: .
          dockerfile: dev.Dockerfile
        ports:
        - "5173:5173"
        volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
        container_name: todo-front-dev
        command: npm run dev -- --host
        environment:
        - VITE_BACKEND_URL=http://localhost:3000