services:
    todo-frontend:
        build:
          context: .
          dockerfile: dev.Dockerfile
        ports:
        - "5173:5173"
        volumes:
        - .:/usr/src/app
        container_name: todo-front-dev